import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import AOSInitializer from "@/components/AOSInitializer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-50 text-slate-800 overflow-x-hidden">
        <Navbar/>
        <AOSInitializer />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
